version: "3"
services:
  es1:
    # build: 
    #   context: .
    image: elasticsearch:7.9.3
    container_name: es1
    expose:
      - 9200
      - 9300
    volumes:
      - ./ela.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  kibana:
    image: kibana:7.9.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      I18N_LOCALE: zh-CN #汉化
    links:
      - es1:elasticsearch
    restart: always
 
